"""Copy the modules the Vercel webhook needs into its own bundle.

deploy/webhook/ is deployed on its own, so it cannot import from src/. The
reminder endpoint needs the appointment store, which is correctness-critical and
must not be maintained twice by hand. This copies it verbatim instead, and
tests/test_webhook_bundle.py fails if the copy drifts.

    uv run python scripts/sync_webhook_bundle.py

Only modules free of livekit-agents can go here: the serverless bundle has
fastapi, livekit-api, google-auth and aiohttp, nothing more.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "voice_agent"
BUNDLE = ROOT / "deploy" / "webhook" / "voice_agent"

MODULES = [
    "__init__.py",
    "config.py",
    "storage/__init__.py",
    "storage/appointments.py",
    "storage/sheets.py",
    "storage/transcripts.py",
    "reminders/__init__.py",
    "reminders/channels.py",
    "reminders/runner.py",
]

BANNER = "# Generated by scripts/sync_webhook_bundle.py. Do not edit here.\n"


def expected(name: str) -> str:
    return BANNER + (SOURCE / name).read_text(encoding="utf-8")


def sync() -> list[str]:
    changed = []
    for name in MODULES:
        target = BUNDLE / name
        target.parent.mkdir(parents=True, exist_ok=True)
        content = expected(name)
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
            changed.append(name)
    return changed


def check() -> list[str]:
    drifted = []
    for name in MODULES:
        target = BUNDLE / name
        if not target.exists() or target.read_text(encoding="utf-8") != expected(name):
            drifted.append(name)
    return drifted


if __name__ == "__main__":
    if "--check" in sys.argv:
        problems = check()
        if problems:
            print("out of sync: " + ", ".join(problems))
            raise SystemExit(1)
        print("webhook bundle is in sync")
    else:
        for name in sync():
            print(f"updated {name}")
        shutil.rmtree(BUNDLE / "__pycache__", ignore_errors=True)
        print("done")
