# Generated by scripts/sync_webhook_bundle.py. Do not edit here.
"""Persistence for anything a call produces."""

from __future__ import annotations

from typing import TYPE_CHECKING

from voice_agent.storage.appointments import (
    REF_DIGITS,
    Appointment,
    AppointmentError,
    AppointmentStore,
    SlotTaken,
    due_for_reminder,
    normalise_number,
)
from voice_agent.storage.sheets import SheetsClient, SheetsError
from voice_agent.storage.transcripts import save_transcript

if TYPE_CHECKING:
    from voice_agent.config import Settings

__all__ = [
    "REF_DIGITS",
    "Appointment",
    "AppointmentError",
    "AppointmentStore",
    "SheetsClient",
    "SheetsError",
    "SlotTaken",
    "build_store",
    "due_for_reminder",
    "normalise_number",
    "save_transcript",
]


def build_store(settings: Settings) -> AppointmentStore | None:
    """The appointment store, or None when the sheet is not configured."""
    if not settings.sheets.is_configured:
        return None
    client = SheetsClient(
        settings.sheets.service_account_json, settings.sheets.spreadsheet_id
    )
    return AppointmentStore(client, tab=settings.sheets.tab)
